remote_theme: Paramdigma/hydryne-jekyll-theme
title: Hydryne testing 4
url: "https://rynne.es"
baseurl: "/hydryne-theme-testing"

data:
  navigation:
    - name: Pricing
      link: /pricing
      new_window: false
      highlight: false
    - name: Blog
      link: /blog
      new_window: false
      highlight: false
    - name: About
      link: /about
      new_window: false
      highlight: false
    - name: Contact
      link: /contact
      new_window: false
      highlight: false
    - name: Sign Up
      link: /
      new_window: true
      highlight: true

collections:
  staff_members:
    _hide_content: true
  data:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty
